-- One-time setup. Run as ACCOUNTADMIN.
-- Creates the data and experiment schemas and grants the RelationalAI Native App
-- what it needs to read the data and to create GNN experiments and models.

CREATE DATABASE IF NOT EXISTS BENEFICIAL_OWNERSHIP;
CREATE SCHEMA IF NOT EXISTS BENEFICIAL_OWNERSHIP.DATA;
CREATE SCHEMA IF NOT EXISTS BENEFICIAL_OWNERSHIP.EXPERIMENTS;

GRANT USAGE ON DATABASE BENEFICIAL_OWNERSHIP TO APPLICATION RELATIONALAI;
GRANT USAGE ON SCHEMA BENEFICIAL_OWNERSHIP.DATA TO APPLICATION RELATIONALAI;
-- FUTURE grants to an application are not allowed, so the data loader re-runs this after creating tables.
GRANT SELECT ON ALL TABLES IN SCHEMA BENEFICIAL_OWNERSHIP.DATA TO APPLICATION RELATIONALAI;
GRANT USAGE ON SCHEMA BENEFICIAL_OWNERSHIP.EXPERIMENTS TO APPLICATION RELATIONALAI;
GRANT CREATE EXPERIMENT ON SCHEMA BENEFICIAL_OWNERSHIP.EXPERIMENTS TO APPLICATION RELATIONALAI;
GRANT CREATE MODEL ON SCHEMA BENEFICIAL_OWNERSHIP.EXPERIMENTS TO APPLICATION RELATIONALAI;
