-- Executed only by scripts/load_fixture.py after verifying the source schema
-- does not exist. {{DATABASE}} and {{SOURCE_SCHEMA}} are validated identifiers.
CREATE SCHEMA {{DATABASE}}.{{SOURCE_SCHEMA}}
  COMMENT = 'rai-retail-delivery-agent-owned:1';

CREATE TABLE {{DATABASE}}.{{SOURCE_SCHEMA}}.DEPOTS (
  DEPOT_ID VARCHAR NOT NULL PRIMARY KEY,
  NODE_ID VARCHAR NOT NULL,
  IS_OPEN BOOLEAN NOT NULL,
  STOCK_UNITS NUMBER(38,0) NOT NULL
) CHANGE_TRACKING = TRUE;

CREATE TABLE {{DATABASE}}.{{SOURCE_SCHEMA}}.STORES (
  STORE_ID VARCHAR NOT NULL PRIMARY KEY,
  NODE_ID VARCHAR NOT NULL
) CHANGE_TRACKING = TRUE;

CREATE TABLE {{DATABASE}}.{{SOURCE_SCHEMA}}.ROADS (
  FROM_NODE_ID VARCHAR NOT NULL,
  TO_NODE_ID VARCHAR NOT NULL,
  TRAVEL_MINUTES FLOAT NOT NULL,
  PRIMARY KEY (FROM_NODE_ID, TO_NODE_ID)
) CHANGE_TRACKING = TRUE;

CREATE TABLE {{DATABASE}}.{{SOURCE_SCHEMA}}.ORDERS (
  ORDER_ID VARCHAR NOT NULL PRIMARY KEY,
  STORE_ID VARCHAR NOT NULL,
  UNITS NUMBER(38,0) NOT NULL,
  DEADLINE_MINUTES FLOAT NOT NULL
) CHANGE_TRACKING = TRUE;

CREATE TABLE {{DATABASE}}.{{SOURCE_SCHEMA}}.DEMO_STATE (
  REVISION NUMBER(38,0) NOT NULL PRIMARY KEY
) CHANGE_TRACKING = TRUE;
